name: Gas Price Tracker

on:
  push:
    branches: ["main"]
  # schedule:
  #   # UTC 20:45 = Toronto 3:45 PM (Winter/EST) / 4:45 PM (Summer/EDT)
  #   - cron: "45 20 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-gas-price-script:
    runs-on: ubuntu-latest
    environment: Gas price
    defaults:
      run:
        working-directory: ./gas-price

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run main.py
        env:
          SENDER_EMAIL: ${{ secrets.USERNAME }}
          SENDER_PASS: ${{ secrets.PASSWORD }}
          USERS: ${{ vars.USERS }}
          ENABLE_EMAIL: ${{ vars.ENABLE_EMAIL }}

        run: python main.py
